--Primer código de la mañana, donde declaramos una excepción:
DECLARE DIVIDE_ZERO EXCEPTION;

V_A INTEGER := 12;

V_B INTEGER := 10;

V_C NUMBER(5, 2) := 0;

BEGIN IF V_B = 0 THEN RAISE DIVIDE_ZERO;

END IF;

V_C := V_A / V_B;

dbms_output.put_line(V_C);

dbms_output.put_line('TERMINO BIEN');

EXCEPTION
WHEN DIVIDE_ZERO THEN dbms_output.put_line('CUIDADO QUE VAS A DIVIDIR POR CERO');

END;

--Un código para copiar la tabla:
DROP TABLE EMP_COPIA;

CREATE TABLE EMP_COPIA AS
SELECT
    *
FROM
    EMP;

/* CONTROLAR QUE UN JEFE NO PUEDA TENER MÁS DE 7 EMPLEADOS A SU CARGO */
CREATE
OR REPLACE TRIGGER NO_MAS_7 BEFORE --BEFORE|AFTER
INSERT
    OR
UPDATE
    OF MGR -- INSERT OR DELETE OR (UPDATE | UPDATE OF COLUMN)
    ON EMP_COPIA FOR EACH ROW DECLARE V_NUM_EMP INTEGER := 0;

BEGIN
SELECT
    COUNT(EMPNO) INTO V_NUM_EMP
FROM
    EMP_COPIA
WHERE
    MGR = :NEW.MGR;

IF V_NUM_EMP >= 7 THEN raise_application_error (
    -20001,
    'ESTE JEFE NO PUEDE TENER MAS DE 7 EMPLEADOS A SU CARGO'
);

END IF;

END;

/ SHOW ERRORS;

/* REALIZAR UNA FUNCIÓN QUE AL PASARLE UN TEXTO CON ACENTOS, ME LA DEVUELVA SIN ACENTOS.
 EL TEXTO DEBE ESTAR EN LA MISMA CAPITALIDAD QUE SE ENCONTRABA */
CREATE
OR REPLACE FUNCTION SIN_TILDE(pTEXTO VARCHAR2) RETURN VARCHAR2 IS BEGIN RETURN(TRANSLATE (pTEXTO, 'áéíóúÁÉÍÓÚ', 'aeiouAEIOU'));

END;

/
SELECT
    SIN_TILDE('ÁLóJá')
from
    dual;

/ DECLARE A VARCHAR2(100);

BEGIN A := SIN_TILDE('ÁLóJá');

dbms_output.put_line(A);

END;

/ --Preguntar el enunciado de lo que aquí abajo hay:
CREATE
OR REPLACE TRIGGER QUITA_TILDES BEFORE
INSERT
    OR
UPDATE
    OF ENAME,
    JOB ON EMP_COPIA FOR EACH ROW BEGIN :NEW.ENAME := SIN_TILDE(:NEW.ENAME);

:NEW.JOB := SIN_TILDE(:NEW.JOB);

END;

/
UPDATE
    EMP_COPIA
SET
    ENAME = ENAME;

/* Conseguir el enunciado */
--TRDEPT_COPIA_EXACTA
--CREATE TABLE DEPT_COPIA_EXACTA AS SELECT * FROM DEPT;
--SELECT * FROM DEPT_COPIA_EXACTA;

CREATE OR REPLACE TRIGGER TRDEPT_COPIA_EXACTA
AFTER
INSERT OR DELETE OR UPDATE
ON DEPT
FOR EACH ROW
BEGIN

  IF UPDATING THEN
    UPDATE DEPT_COPIA_EXACTA
    SET DNAME = :NEW.DNAME,
        LOC = :NEW.LOC,
        DEPTNO = :NEW.DEPTNO
    WHERE DEPTNO = :OLD.DEPTNO;

  END IF;    

  IF INSERTING THEN
    INSERT INTO DEPT_COPIA_EXACTA(DEPTNO, DNAME,LOC)    VALUES(:NEW.DEPTNO,:NEW.DNAME,:NEW.LOC);

  END IF;
  
  IF DELETING THEN
   DELETE FROM DEPT_COPIA_EXACTA WHERE DEPTNO = :OLD.DEPTNO;
  END IF;
    
END;
/
SHOW ERRORS;
/

--INSERT INTO DEPT VALUES (53, 'FRAN', 'TA FLOJO');
UPDATE DEPT
SET DNAME = 'NACHO',
    LOC = 'CALLATE'
WHERE DEPTNO = 69;

DELETE FROM DEPT WHERE DNAME ='NACHO';

SELECT * FROM DEPT_COPIA_EXACTA WHERE DEPTNO >=50
