/*
INSERT ---- C 
SELECT ---- R
UPDATE ---- U
DELETE ---- D
*/
-- INSERT INTO TABLA (COL1....COLN) VALUES (V1....VN);
-- INSERT INTO DEPT2 (DEPTNO,LOC, DNAME) VALUES (90, 'SEVILLA', 'EXPEDICIONES');
INSERT INTO DEPT3    
SELECT DEPT.DEPTNO, DNAME, SUM(SAL)
FROM DEPT, EMP
WHERE EMP.DEPTNO = DEPT.DEPTNO
GROUP BY DEPT.DEPTNO, DNAME;
--SELECT * FROM DEPT3;
--DELETE FROM DEPT3;


/*DROP TABLE DEPT3;
CREATE TABLE DEPT3 AS SELECT * FROM DEPT2;
*/

UPDATE DEPT3
 SET LOC = 'JOSE ANGEL2',
     DNAME = 'JOSE ANGEL',
     DEPTNO =DEPTNO +1
WHERE DEPTNO = 30 ;

SELECT * FROM DEPT3;


/*DROP TABLE DEPT3;
CREATE TABLE DEPT3 AS SELECT * FROM DEPT2;
*/
/*
DELETE FROM DEPT3
WHERE LOC = 'GAMIZ';

SELECT * FROM DEPT3;
*/
ROLLBACK;

DELETE FROM DEPT3
WHERE DEPTNO NOT IN (SELECT DEPTNO FROM EMP);

SELECT * FROM DEPT3;